# Prepara y estructura datos con Python II 🐍🖥️✍️

## Objetivos academicos

## Pandas para análisis de datos 🐼📊

---

### Resumen 🔃

**pandas** es la librería fundamental de Python para manipular, limpiar y analizar datos estructurados. Su nombre proviene de *Panel Data* y está construida sobre **NumPy**, lo que le da gran velocidad y flexibilidad para trabajar con grandes volúmenes de información. Algunos métodos y atributos que vimos en la sesión anterior fueron:  

- `read_csv()` : Sirve para cargar datos desde archivos CSV.  
- `shape` : Atributo que muestra la forma del DataFrame, es decir, el número de filas y columnas.  
- `columns` : Atributo que devuelve el listado con los nombres de las columnas del DataFrame.  
- `info()` : Método que muestra un resumen general del DataFrame (tipos de datos, valores nulos, memoria usada, etc.).  
- `head()` : Método que muestra las primeras filas del DataFrame (por defecto las primeras 5).  
- `drop()` : Método que permite eliminar columnas o filas específicas.  
- `rename()` : Método que se utiliza para cambiar el nombre de columnas o índices.  
- `describe()` : Método que calcula estadísticas descriptivas básicas de las columnas numéricas del DataFrame.  
- `[[]]`: Combinación para la selección de columnas

> 💡 Estos métodos y atributos son esenciales para explorar y comprender la estructura de tus datos antes de realizar cualquier análisis más avanzado.

### 🏋️🤸 Práctica previa al tema de la sesión

In [88]:
import pandas as pd  # ¿Pa' qué servia esto?

**Carga los datos y responde**

In [89]:
emission_co2=pd.read_csv('https://practicum-content.s3.us-west-1.amazonaws.com/datasets/co2-emissions.csv')

In [90]:
emission_co2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26540 entries, 0 to 26539
Data columns (total 5 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Entity                             26540 non-null  object
 1   Year                               26528 non-null  object
 2   Annual CO₂ emissions (per capita)  25534 non-null  object
 3   date                               26540 non-null  object
 4   unit_2                             25809 non-null  object
dtypes: object(5)
memory usage: 1.0+ MB

**¿Cuántos datos y cuántas columnas tienes?**

**Describe un poco tus datos. Es decir, muestra algunos cuántos, dime cómo están constituidos, dime algunas estádisticas al respecto, hablame sobre la calidad de ellos**

**Crea una variable que se llame `df_selection` y guarda en ella los datos de las columnas ` Entity,Year,date`**

**De `df_selection` :**

- Renombra `Year` como `year`.
- Elimina la columna `date`

### 🧼 Limpieza y transformación de datos

#### **Formatear datos**

**Formatear cadenas de texto**

Veamos las necesidades de limpieza de la columna `Entity`

In [91]:
#Valores únicos de la columna
print(emission_co2['Entity'].nunique())
emission_co2['Entity'].unique().tolist()

690

['Afghanistan',
 'Afghanistan ',
 'afghanistan',
 'Africa',
 'Africa ',
 'africa',
 ' Africa',
 'Albania',
 'Albania ',
 'Algeria',
 'algeria',
 ' Algeria',
 'Algeria ',
 'Andorra',
 'Angola',
 'Angola ',
 'angola',
 'Anguilla',
 ' Anguilla',
 'Antigua and Barbuda',
 'Antigua And Barbuda',
 'Antigua and Barbuda ',
 'antigua and barbuda',
 'Argentina',
 'Argentina ',
 ' Argentina',
 'Armenia',
 ' Armenia',
 'Armenia ',
 'armenia',
 'Aruba',
 'Aruba ',
 'aruba',
 ' Aruba',
 'Asia',
 'asia',
 'Asia (excl. China and India)',
 'Asia (Excl. China And India)',
 ' Asia (excl. China and India)',
 'asia (excl. china and india)',
 'Asia (excl. China and India) ',
 'Australia',
 ' Australia',
 'Australia ',
 'australia',
 'Austria',
 'austria',
 ' Austria',
 'Austria ',
 'Azerbaijan',
 ' Azerbaijan',
 'azerbaijan',
 'Bahamas',
 ' Bahamas',
 'Bahamas ',
 'Bahrain',
 'Bahrain ',
 'bahrain',
 'Bangladesh',
 'Bangladesh ',
 ' Bangladesh',
 'bangladesh',
 'Barbados',
 'Barbados ',
 'Belarus',
 ' Belarus',
 'Belarus ',
 'belarus',
 'Belgium',
 'belgium',
 ' Belgium',
 'Belgium ',
 'Belize',
 ' Belize',
 'Belize ',
 'Benin',
 ' Benin',
 'Benin ',
 'Bermuda',
 ' Bermuda',
 'Bermuda ',
 'Bhutan',
 ' Bhutan',
 'Bhutan ',
 'Bolivia',
 ' Bolivia',
 'bolivia',
 'Bolivia ',
 'Bonaire Sint Eustatius and Saba',
 'Bonaire Sint Eustatius And Saba',
 'Bosnia and Herzegovina',
 'bosnia and herzegovina',
 'Bosnia and Herzegovina ',
 ' Bosnia and Herzegovina',
 'Bosnia And Herzegovina',
 'Botswana',
 'Botswana ',
 'Brazil',
 'Brazil ',
 ' Brazil',
 'British Virgin Islands',
 'British Virgin Islands ',
 'british virgin islands',
 'Brunei',
 'brunei',
 'Bulgaria',
 ' Bulgaria',
 'Burkina Faso',
 'burkina faso',
 'Burundi',
 'burundi',
 ' Burundi',
 'Burundi ',
 'Cambodia',
 'cambodia',
 'Cameroon',
 'cameroon',
 'Canada',
 'canada',
 'Canada ',
 ' Canada',
 'Cape Verde',
 'Cape Verde ',
 'cape verde',
 'Central African Republic',
 ' Central African Republic',
 'Chad',
 'Chad ',
 'Chile',
 'Chile ',
 ' Chile',
 'China',
 'china',
 'China ',
 ' China',
 'Colombia',
 'colombia',
 ' Colombia',
 'Colombia ',
 'Comoros',
 'comoros',
 ' Comoros',
 'Congo',
 'congo',
 'Cook Islands',
 'Costa Rica',
 'Costa Rica ',
 ' Costa Rica',
 "Cote d'Ivoire",
 " Cote d'Ivoire",
 "Cote D'Ivoire",
 "Cote d'Ivoire ",
 'Croatia',
 'croatia',
 'Cuba',
 'Cuba ',
 'cuba',
 'Curacao',
 'Curacao ',
 'Cyprus',
 'cyprus',
 'Czechia',
 'czechia',
 'Czechia ',
 'Democratic Republic of Congo',
 ' Democratic Republic of Congo',
 'Denmark',
 'denmark',
 'Denmark ',
 'Djibouti',
 'djibouti',
 'Djibouti ',
 'Dominica',
 'dominica',
 'Dominican Republic',
 'dominican republic',
 ' Dominican Republic',
 'East Timor',
 'East Timor ',
 'Ecuador',
 'Ecuador ',
 ' Ecuador',
 'ecuador',
 'Egypt',
 'egypt',
 'Egypt ',
 ' Egypt',
 'El Salvador',
 'el salvador',
 'El Salvador ',
 'Equatorial Guinea',
 'equatorial guinea',
 'Eritrea',
 'Estonia',
 ' Estonia',
 'Estonia ',
 'Eswatini',
 'eswatini',
 ' Eswatini',
 'Eswatini ',
 'Ethiopia',
 ' Ethiopia',
 'ethiopia',
 'Europe',
 'Europe ',
 ' Europe',
 'europe',
 'Europe (excl. EU-27)',
 'europe (excl. eu-27)',
 ' Europe (excl. EU-27)',
 'Europe (excl. EU-27) ',
 'Europe (Excl. Eu-27)',
 'Europe (excl. EU-28)',
 'Europe (Excl. Eu-28)',
 'Europe (excl. EU-28) ',
 'europe (excl. eu-28)',
 ' Europe (excl. EU-28)',
 'European Union (27)',
 'European Union (27) ',
 ' European Union (27)',
 'european union (27)',
 'European Union (28)',
 'European Union (28) ',
 ' European Union (28)',
 'european union (28)',
 'Faroe Islands',
 'Fiji',
 'Fiji ',
 ' Fiji',
 'Finland',
 ' Finland',
 'finland',
 'Finland ',
 'France',
 'france',
 'France ',
 'French Polynesia',
 'french polynesia',
 'Gabon',
 ' Gabon',
 'gabon',
 'Gambia',
 'Gambia ',
 'gambia',
 ' Gambia',
 'Georgia',
 'georgia',
 'Georgia ',
 ' Georgia',
 'Germany',
 'Germany ',
 'germany',
 ' Germany',
 'Ghana',
 'ghana',
 'Greece',
 'greece',
 'Greece ',
 ' Greece',
 'Greenland',
 'greenland',
 ' Greenland',
 'Grenada',
 ' Grenada',
 'Guatemala',
 ' Guatemala',
 'guatemala',
 'Guatemala ',
 'Guinea',
 'Guinea ',
 ' Guinea',
 'Guinea-Bissau',
 'guinea-bissau',
 'Guinea-Bissau ',
 'Guyana',
 'guyana',
 'Guyana ',
 'Haiti',
 ' Haiti',
 'haiti',
 'High-income countries',
 ' High-income countries',
 'High-income countries ',
 'high-income countries',
 'Honduras',
 ' Honduras',
 'Honduras ',
 'honduras',
 'Hong Kong',
 'Hong Kong ',
 'Hungary',
 'Hungary ',
 ' Hungary',
 'hungary',
 'Iceland',
 'iceland',
 'India',
 ' India',
 'india',
 'India ',
 'Indonesia',
 'indonesia',
 ' Indonesia',
 'Indonesia ',
 'Iran',
 'iran',
 ' Iran',
 'Iraq',
 'iraq',
 'Iraq ',
 ' Iraq',
 'Ireland',
 'ireland',
 'Ireland ',
 'Israel',
 'Israel ',
 ' Israel',
 'Italy',
 ' Italy',
 'Jamaica',
 'Japan',
 'Japan ',
 'Jordan',
 ' Jordan',
 'Jordan ',
 'Kazakhstan',
 'kazakhstan',
 'Kazakhstan ',
 ' Kazakhstan',
 'Kenya',
 'Kenya ',
 'Kiribati',
 'Kiribati ',
 ' Kiribati',
 'Kosovo',
 'kosovo',
 'Kosovo ',
 'Kuwait',
 'Kyrgyzstan',
 ' Kyrgyzstan',
 'Kyrgyzstan ',
 'Laos',
 'Laos ',
 ' Laos',
 'Latvia',
 'Latvia ',
 ' Latvia',
 'latvia',
 'Lebanon',
 'lebanon',
 'Lebanon ',
 'Lesotho',
 ' Lesotho',
 'lesotho',
 'Lesotho ',
 'Liberia',
 'Libya',
 ' Libya',
 'Liechtenstein',
 'Liechtenstein ',
 'Lithuania',
 ' Lithuania',
 'lithuania',
 'Low-income countries',
 ' Low-income countries',
 'Low-Income Countries',
 'low-income countries',
 'Low-income countries ',
 'Lower-middle-income countries',
 'Lower-middle-income countries ',
 ' Lower-middle-income countries',
 'Lower-Middle-Income Countries',
 'Luxembourg',
 ' Luxembourg',
 'Macao',
 'macao',
 ' Macao',
 'Madagascar',
 'Malawi',
 'malawi',
 'Malaysia',
 ' Malaysia',
 'malaysia',
 'Malaysia ',
 'Maldives',
 'maldives',
 'Mali',
 'Malta',
 ' Malta',
 'Marshall Islands',
 'Mauritania',
 'Mauritania ',
 'Mauritius',
 'Mauritius ',
 'mauritius',
 'Mexico',
 'mexico',
 'Mexico ',
 ' Mexico',
 'Micronesia (country)',
 ' Micronesia (country)',
 'Micronesia (Country)',
 'Moldova',
 'Moldova ',
 ' Moldova',
 'moldova',
 'Mongolia',
 ' Mongolia',
 'Mongolia ',
 'Montenegro',
 'montenegro',
 'Montenegro ',
 ' Montenegro',
 'Montserrat',
 ' Montserrat',
 'Montserrat ',
 'Morocco',
 ' Morocco',
 'morocco',
 'Mozambique',
 'Mozambique ',
 'Myanmar',
 'Myanmar ',
 ' Myanmar',
 'Namibia',
 'Nauru',
 'Nauru ',
 ' Nauru',
 'nauru',
 'Nepal',
 ' Nepal',
 'nepal',
 'Nepal ',
 'Netherlands',
 'Netherlands ',
 'netherlands',
 'New Caledonia',
 ' New Caledonia',
 'new caledonia',
 'New Zealand',
 ' New Zealand',
 'New Zealand ',
 'new zealand',
 'Nicaragua',
 'nicaragua',
 'Niger',
 ' Niger',
 'Niger ',
 'Nigeria',
 ' Nigeria',
 'Nigeria ',
 'nigeria',
 'Niue',
 ' Niue',
 'North America',
 'north america',
 'North America ',
 ' North America',
 'North America (excl. USA)',
 'North America (excl. USA) ',
 'north america (excl. usa)',
 'North Korea',
 'north korea',
 'North Korea ',
 'North Macedonia',
 'North Macedonia ',
 'north macedonia',
 ' North Macedonia',
 'Norway',
 'Norway ',
 'norway',
 'Oceania',
 ' Oceania',
 'Oceania ',
 'oceania',
 'Oman',
 'Oman ',
 'oman',
 'Pakistan',
 'Pakistan ',
 'pakistan',
 'Palau',
 'palau',
 'Palestine',
 'palestine',
 'Panama',
 'Panama ',
 'panama',
 ' Panama',
 'Papua New Guinea',
 'Papua New Guinea ',
 'papua new guinea',
 'Paraguay',
 'paraguay',
 ' Paraguay',
 'Peru',
 'peru',
 'Peru ',
 'Philippines',
 'philippines',
 'Philippines ',
 ' Philippines',
 'Poland',
 ' Poland',
 'Poland ',
 'poland',
 'Portugal',
 'portugal',
 'Portugal ',
 ' Portugal',
 'Qatar',
 ' Qatar',
 'Qatar ',
 'Romania',
 'romania',
 'Romania ',
 ' Romania',
 'Russia',
 'russia',
 ' Russia',
 'Russia ',
 'Rwanda',
 ' Rwanda',
 'Rwanda ',
 'Saint Helena',
 'saint helena',
 ' Saint Helena',
 'Saint Kitts and Nevis',
 'Saint Kitts And Nevis',
 'Saint Lucia',
 ' Saint Lucia',
 'Saint Lucia ',
 'Saint Pierre and Miquelon',
 ' Saint Pierre and Miquelon',
 'saint pierre and miquelon',
 'Saint Pierre and Miquelon ',
 'Saint Pierre And Miquelon',
 'Saint Vincent and the Grenadines',
 ' Saint Vincent and the Grenadines',
 'Saint Vincent and the Grenadines ',
 'Samoa',
 'samoa',
 ' Samoa',
 'Sao Tome and Principe',
 'Sao Tome And Principe',
 'sao tome and principe',
 'Saudi Arabia',
 'Saudi Arabia ',
 'saudi arabia',
 'Senegal',
 'senegal',
 'Serbia',
 ' Serbia',
 'serbia',
 'Serbia ',
 'Seychelles',
 ' Seychelles',
 'Seychelles ',
 'Sierra Leone',
 'sierra leone',
 'Sierra Leone ',
 'Singapore',
 'singapore',
 'Singapore ',
 'Sint Maarten (Dutch part)',
 ' Sint Maarten (Dutch part)',
 'Sint Maarten (Dutch part) ',
 'Slovakia',
 ' Slovakia',
 'Slovenia',
 'Slovenia ',
 ' Slovenia',
 'slovenia',
 'Solomon Islands',
 'Somalia',
 ' Somalia',
 'Somalia ',
 'South Africa',
 ' South Africa',
 'South Africa ',
 'South America',
 'South America ',
 ' South America',
 'south america',
 'South Korea',
 'South Korea ',
 ' South Korea',
 'South Sudan',
 'South Sudan ',
 'south sudan',
 ' South Sudan',
 'Spain',
 'Spain ',
 ' Spain',
 'spain',
 'Sri Lanka',
 'sri lanka',
 'Sudan',
 ' Sudan',
 'sudan',
 'Suriname',
 'suriname',
 'Suriname ',
 'Sweden',
 ' Sweden',
 'Switzerland',
 'Syria',
 ' Syria',
 'Syria ',
 'syria',
 'Taiwan',
 'taiwan',
 ' Taiwan',
 'Tajikistan',
 ' Tajikistan',
 'Tajikistan ',
 'Tanzania',
 'tanzania',
 ' Tanzania',
 'Thailand',
 ' Thailand',
 'Thailand ',
 'Togo',
 'togo',
 ' Togo',
 'Tonga',
 'Trinidad and Tobago',
 'Trinidad And Tobago',
 'Tunisia',
 'tunisia',
 ' Tunisia',
 'Turkey',
 ' Turkey',
 'Turkmenistan',
 ' Turkmenistan',
 'Turkmenistan ',
 'Turks And Caicos Islands',
 'Turks and Caicos Islands',
 'Tuvalu',
 ' Tuvalu',
 'Uganda',
 'Uganda ',
 'Ukraine',
 'ukraine',
 'Ukraine ',
 'United Arab Emirates',
 ' United Arab Emirates',
 'United Kingdom',
 ' United Kingdom',
 'united kingdom',
 'United Kingdom ',
 'United States',
 'United States ',
 ' United States',
 'united states',
 'Upper-middle-income countries',
 'upper-middle-income countries',
 ' Upper-middle-income countries',
 'Upper-middle-income countries ',
 'Uruguay',
 ' Uruguay',
 'uruguay',
 'Uzbekistan',
 'Uzbekistan ',
 ' Uzbekistan',
 'uzbekistan',
 'Vanuatu',
 'Vanuatu ',
 'Venezuela',
 ' Venezuela',
 'venezuela',
 'Vietnam',
 'Vietnam ',
 'vietnam',
 ' Vietnam',
 'Wallis and Futuna',
 'Wallis and Futuna ',
 ' World',
 'World',
 'World ',
 'world',
 'Yemen',
 ' Yemen',
 'yemen',
 'Zambia',
 'Zambia ',
 ' Zambia',
 'zambia',
 'Zimbabwe',
 'zimbabwe']

In [92]:
# Convertir texto a minúsculas
emission_co2["Entity"] = emission_co2["Entity"].str.lower()

**Pon en practica 🏋️✍️** 

Prueba los efecto de usar:

- `str.upper()` -> Convertir a mayúsculas
- `str.title()` -> Convertir primer letra a mayúscula
- `str.strip()` -> Remover espacios extras
- `str.replace()` -> Reemplazar cadenas de texto

In [93]:
emission_co2["Entity"]=emission_co2["Entity"].str.strip()
emission_co2["Entity"]=emission_co2["Entity"].str.replace('"','')
emission_co2["Entity"]=emission_co2["Entity"].str.upper()

In [94]:
# Tambien podemos aplicar varios cambios encadenados
emission_co2["Entity"]=emission_co2["Entity"].str.strip().str.replace('"','').str.upper()

In [95]:
print(emission_co2['Entity'].nunique())
emission_co2['Entity'].unique().tolist()

231

['AFGHANISTAN',
 'AFRICA',
 'ALBANIA',
 'ALGERIA',
 'ANDORRA',
 'ANGOLA',
 'ANGUILLA',
 'ANTIGUA AND BARBUDA',
 'ARGENTINA',
 'ARMENIA',
 'ARUBA',
 'ASIA',
 'ASIA (EXCL. CHINA AND INDIA)',
 'AUSTRALIA',
 'AUSTRIA',
 'AZERBAIJAN',
 'BAHAMAS',
 'BAHRAIN',
 'BANGLADESH',
 'BARBADOS',
 'BELARUS',
 'BELGIUM',
 'BELIZE',
 'BENIN',
 'BERMUDA',
 'BHUTAN',
 'BOLIVIA',
 'BONAIRE SINT EUSTATIUS AND SABA',
 'BOSNIA AND HERZEGOVINA',
 'BOTSWANA',
 'BRAZIL',
 'BRITISH VIRGIN ISLANDS',
 'BRUNEI',
 'BULGARIA',
 'BURKINA FASO',
 'BURUNDI',
 'CAMBODIA',
 'CAMEROON',
 'CANADA',
 'CAPE VERDE',
 'CENTRAL AFRICAN REPUBLIC',
 'CHAD',
 'CHILE',
 'CHINA',
 'COLOMBIA',
 'COMOROS',
 'CONGO',
 'COOK ISLANDS',
 'COSTA RICA',
 "COTE D'IVOIRE",
 'CROATIA',
 'CUBA',
 'CURACAO',
 'CYPRUS',
 'CZECHIA',
 'DEMOCRATIC REPUBLIC OF CONGO',
 'DENMARK',
 'DJIBOUTI',
 'DOMINICA',
 'DOMINICAN REPUBLIC',
 'EAST TIMOR',
 'ECUADOR',
 'EGYPT',
 'EL SALVADOR',
 'EQUATORIAL GUINEA',
 'ERITREA',
 'ESTONIA',
 'ESWATINI',
 'ETHIOPIA',
 'EUROPE',
 'EUROPE (EXCL. EU-27)',
 'EUROPE (EXCL. EU-28)',
 'EUROPEAN UNION (27)',
 'EUROPEAN UNION (28)',
 'FAROE ISLANDS',
 'FIJI',
 'FINLAND',
 'FRANCE',
 'FRENCH POLYNESIA',
 'GABON',
 'GAMBIA',
 'GEORGIA',
 'GERMANY',
 'GHANA',
 'GREECE',
 'GREENLAND',
 'GRENADA',
 'GUATEMALA',
 'GUINEA',
 'GUINEA-BISSAU',
 'GUYANA',
 'HAITI',
 'HIGH-INCOME COUNTRIES',
 'HONDURAS',
 'HONG KONG',
 'HUNGARY',
 'ICELAND',
 'INDIA',
 'INDONESIA',
 'IRAN',
 'IRAQ',
 'IRELAND',
 'ISRAEL',
 'ITALY',
 'JAMAICA',
 'JAPAN',
 'JORDAN',
 'KAZAKHSTAN',
 'KENYA',
 'KIRIBATI',
 'KOSOVO',
 'KUWAIT',
 'KYRGYZSTAN',
 'LAOS',
 'LATVIA',
 'LEBANON',
 'LESOTHO',
 'LIBERIA',
 'LIBYA',
 'LIECHTENSTEIN',
 'LITHUANIA',
 'LOW-INCOME COUNTRIES',
 'LOWER-MIDDLE-INCOME COUNTRIES',
 'LUXEMBOURG',
 'MACAO',
 'MADAGASCAR',
 'MALAWI',
 'MALAYSIA',
 'MALDIVES',
 'MALI',
 'MALTA',
 'MARSHALL ISLANDS',
 'MAURITANIA',
 'MAURITIUS',
 'MEXICO',
 'MICRONESIA (COUNTRY)',
 'MOLDOVA',
 'MONGOLIA',
 'MONTENEGRO',
 'MONTSERRAT',
 'MOROCCO',
 'MOZAMBIQUE',
 'MYANMAR',
 'NAMIBIA',
 'NAURU',
 'NEPAL',
 'NETHERLANDS',
 'NEW CALEDONIA',
 'NEW ZEALAND',
 'NICARAGUA',
 'NIGER',
 'NIGERIA',
 'NIUE',
 'NORTH AMERICA',
 'NORTH AMERICA (EXCL. USA)',
 'NORTH KOREA',
 'NORTH MACEDONIA',
 'NORWAY',
 'OCEANIA',
 'OMAN',
 'PAKISTAN',
 'PALAU',
 'PALESTINE',
 'PANAMA',
 'PAPUA NEW GUINEA',
 'PARAGUAY',
 'PERU',
 'PHILIPPINES',
 'POLAND',
 'PORTUGAL',
 'QATAR',
 'ROMANIA',
 'RUSSIA',
 'RWANDA',
 'SAINT HELENA',
 'SAINT KITTS AND NEVIS',
 'SAINT LUCIA',
 'SAINT PIERRE AND MIQUELON',
 'SAINT VINCENT AND THE GRENADINES',
 'SAMOA',
 'SAO TOME AND PRINCIPE',
 'SAUDI ARABIA',
 'SENEGAL',
 'SERBIA',
 'SEYCHELLES',
 'SIERRA LEONE',
 'SINGAPORE',
 'SINT MAARTEN (DUTCH PART)',
 'SLOVAKIA',
 'SLOVENIA',
 'SOLOMON ISLANDS',
 'SOMALIA',
 'SOUTH AFRICA',
 'SOUTH AMERICA',
 'SOUTH KOREA',
 'SOUTH SUDAN',
 'SPAIN',
 'SRI LANKA',
 'SUDAN',
 'SURINAME',
 'SWEDEN',
 'SWITZERLAND',
 'SYRIA',
 'TAIWAN',
 'TAJIKISTAN',
 'TANZANIA',
 'THAILAND',
 'TOGO',
 'TONGA',
 'TRINIDAD AND TOBAGO',
 'TUNISIA',
 'TURKEY',
 'TURKMENISTAN',
 'TURKS AND CAICOS ISLANDS',
 'TUVALU',
 'UGANDA',
 'UKRAINE',
 'UNITED ARAB EMIRATES',
 'UNITED KINGDOM',
 'UNITED STATES',
 'UPPER-MIDDLE-INCOME COUNTRIES',
 'URUGUAY',
 'UZBEKISTAN',
 'VANUATU',
 'VENEZUELA',
 'VIETNAM',
 'WALLIS AND FUTUNA',
 'WORLD',
 'YEMEN',
 'ZAMBIA',
 'ZIMBABWE']

**Convertir valores numéricos**

In [96]:
emission_co2['Annual CO₂ emissions (per capita)'].unique().tolist()

['0.0019921463',
 '0.010837197',
 '0.011625335',
 '0.011467511',
 '0.013123366',
 '0.012945492',
 '0.018480647',
 '0.021669438',
 '0.034129996',
 '0.037801724',
 '0.04335994',
 '0.045808833',
 '0.05326608',
 '0.07322033',
 '0.07358391',
 '0.085441604',
 '0.10033048',
 '0.106284514',
 '0.122013114',
 '0.11373056',
 '0.08543128',
 '0.14795192',
 '0.1636936',
 '0.12910292',
 '0.1345167',
 '0.15343112',
 '0.16607082',
 '0.15167534',
 '0.1787136',
 '0.15819776',
 '0.16350494',
 '0.13336322',
 '0.16573393',
 '0.19056578',
 '0.2308076',
 '0.25214335',
 '0.30642045',
 '0.27439797',
 '0.27343473',
 '0.24792345',
 '0.23284777',
 '0.16805434',
 '0.15641147',
 '0.111609',
 '0.0995065',
 '0.089462',
 '0.08305054',
 '0.07713131',
 '0.0706777',
 '0.06672778',
 '0.054889955',
 '0.052017417',
 '0.05270568',
 '0.062727444',
 '0.06860504',
 '0.052513268',
 nan,
 '0.08493193',
 '0.10806349',
 '0.1606516',
 '0.23271915',
 '0.2957424',
 '0.4033813',
 '0.32838032',
 '0.29183197',
 '0.27707645',
 '0.2858314',
 '0.25666347',
 '0.27116078',
 '0.2885413',
 '0.28595492',
 '0.29706252',
 '0.2567944',
 '0.26017997',
 '0.2658372',
 '0.00016810493',
 '0.00027865346',
 '0.00036027696',
 '0.00035830968',
 '0.00060305005',
 '0.0009820405',
 '0.0022003131',
 '0.0021923848',
 '0.013219625',
 '0.017834708',
 '0.024409406',
 '0.031057494',
 '0.034764815',
 '0.043902785',
 '0.039936516',
 '0.016815761',
 '0.028121473',
 '0.04176499',
 '0.056402333',
 '0.06341765',
 '0.07276437',
 '0.0909625',
 '0.09390756',
 '0.10735923',
 '0.12100435',
 '0.116731',
 '0.123760745',
 '0.13460414',
 '0.13367727',
 '0.13349853',
 '0.15768538',
 '0.17112114',
 '0.16625711',
 '0,17010342',
 '0.18615878',
 '0.18404068',
 '0.15595937',
 '0.18666829',
 '0.19445343',
 '0.20180704',
 '0.21327865',
 '0.2069944',
 '0.21005066',
 '0.21359752',
 '0.19853099',
 '0.17142504',
 '0.15295953',
 '0.16163766',
 '0.18227975',
 '0.19862159',
 '0.21307538',
 '0.22562651',
 '0.23430876',
 '0.24609981',
 '0.25714242',
 '0.27570948',
 '0.2956288',
 '0.3243292',
 '0.32344264',
 '0.32124582',
 '0.32733774',
 '0.34674028',
 '0.41701305',
 '0.43538994',
 '0.4650465',
 '0.46213555',
 '0.47455564',
 '0.51107895',
 '0.52181756',
 '0.53480226',
 '0.5492976',
 '0.53397065',
 '0.5522528',
 '0.5578653',
 '0.55908394',
 '0.57831824',
 '0.61948013',
 '0.66652215',
 '0.6725036',
 '0.7027146',
 '0.7429979',
 '0.7812512',
 '0.8285632',
 '0.88492876',
 '0.9141623',
 '0.95599747',
 '0.95552486',
 '0.9262899',
 '0.97684073',
 '0.97943056',
 '1.0164287',
 '1.0650722',
 '1.1113187',
 '1.1046573',
 '1.1166936',
 '1.1277032',
 '1.1966531',
 '1.191995',
 '1.2000366',
 '1.1665251',
 '1.1920505',
 '1.1169115',
 '1.0240961',
 '1.041674',
 '0.9838701',
 '1.0155436',
 '1.107567',
 '1.154304',
 '1.1624247',
 '1.1620444',
 '1.1567284',
 '1.1124499',
 '1.1223302',
 '1.0824622',
 '1.0319118',
 '1.1064153',
 '1.139779',
 '1.1255214',
 '1.1300635',
 '1.1555071',
 '1.119719',
 '1.1362721',
 '1.1445001',
 '1.125614',
 '1.1082679',
 '1.1428827',
 '1.0937093',
 '1.1004659',
 '1.0873753',
 '1.0554873',
 '1.0988438',
 '0.98307353',
 '1.0208932',
 '0.99125665',
 '0.95925564',
 '0.007159781',
 '0.0070867664',
 '0.017536236',
 '0.12147333',
 '0.27826673',
 '0.32309836',
 '0.39708453',
 '0.62906545',
 '0.562687',
 '0.66028625',
 '0.4049297',
 '0.13336176',
 '0.10353056',
 '0.40916798',
 '0.774856',
 '0.58099794',
 '0.8254675',
 '0.23778823',
 '0.3157255',
 '0.28559932',
 '0.30811167',
 '0.3634157',
 '0.4672824',
 '0.5757659',
 '1.005109',
 '0.77816',
 '0.9048903',
 '1.2260456',
 '1,3412595',
 '1.4117554',
 '1.1615194',
 '1.0940837',
 '1.1466713',
 '1.3074435',
 '1.333065',
 '1.4835377',
 '1.5239673',
 '1.7143964',
 '1.9454285',
 '2.462789',
 '2.2551887',
 '1.809418',
 '1.870237',
 '1.9705406',
 '2.2275915',
 '2.4732132',
 '2.8283699',
 '1.8903238',
 '2.6302996',
 '2.5668557',
 '2.6266687',
 '2.6394625',
 '2.6043959',
 '2.6097698',
 '2.3650215',
 '2.2811687',
 '2.7561815',
 '1.6841552',
 '1.3069565',
 '0.7668275',
 '0.71327627',
 '0.5884248',
 '0.64109814',
 '0.62159795',
 '0.47776133',
 '0.5466155',
 '0.9365232',
 '0.9553966',
 '1.0230986',
 '1.1959662',
 '1.3801702',
 '1.3478992',
 '1.3853046',
 '1.2818633',
 '1.3063571',
 '1.4691418',
 '1.4879525',
 '1.6334258',
 ' -',
 '1.6666856',
 '1.8185163',
 '2.0661745',
 '1.625643',
 '1.5984093',
 '1.8262942',
 '1.6912805',
 '1.6731111',
 '1.6403993',
 '1.8016726',
 '1.8295889',
 '1.8296235',
 '0.0006419031',
 '0.0012771984',
 '0.0031769325',
 '0.0037603965',
 '0.0043493058',
 '0.0043066936',
 '0.0024340036',
 '0.00481467',
 '0.005357156',
 '0.0064758947',
 '0.009316276',
 '0.011485059',
 '0.012478749',
 '0.012864212',
 '0.014877537',
 '0.016805604',
 '0.017591037',
 '0.019898007',
 '0.018538017',
 '0.0070609855',
 '0.009429192',
 '0.0044057337',
 '0.021176292',
 '0.030772531',
 '0.03960487',
 '0.06239821',
 '0.057818197',
 '0.060518295',
 '0.0736583',
 '0.089851215',
 '0.08638843',
 '0.09181947',
 '0.10236545',
 '0.41954175',
 '0.4456566',
 '0.40847814',
 '0.4092041',
 '0.4146334',
 '0.449535',
 '0.47652793',
 '0.51663953',
 '0.47601697',
 '0.5055593',
 '0.5384051',
 '0.52076566',
 '0.47971538',
 '0.45227',
 '0.46331143',
 '0.5327951',
 '0.6688496',
 '0.65482384',
 '0.6870493',
 '0.8357823',
 '1.0925177',
 '1.3227614',
 '1.9631588',
 '2.5913622',
 '2.1063628',
 '2.041075',
 '2.3847072',
 '2.4591527',
 '3.56745',
 '2.5251663',
 '3.5694008',
 '2.5539258',
 '3.3352125',
 '3.2991314',
 '3.3448546',
 '3.5780938',
 '3.4719884',
 '3.2239916',
 '3.0240457',
 '3.032439',
 '2.9999099',
 '3.0041368',
 '3.177377',
 '3.3992364',
 '3.4457092',
 '2.9875426',
 '3.544822',
 '3.000854',
 '2.7633605',
 '2,7716517',
 '2.856378',
 '2.9394941',
 '2.810881',
 '3.3523104',
 '3.1494687',
 '3.214136',
 '3.3489673',
 '3.2704897',
 '3.3897867',
 '3.6039338',
 '3.6649592',
 '3.8587592',
 '4.0002337',
 '3.8795311',
 '3.9620206',
 '4.063172',
 '4.1554093',
 '3.8185709',
 '4.0123305',
 '4.058238',
 '7.729664',
 '7.174049',
 '6.753973',
 '6.483624',
 '6.292708',
 '6.647648',
 '7.0983343',
 '7.189642',
 '7.5072784',
 '7.80381',
 '7.974552',
 '7.953851',
 '7.9858103',
 '7.696261',
 '7.540717',
 '7.4286895',
 '6.857717',
 '6.57633',
 '6.449391',
 '6.157102',
 '6.399643',
 '6.310664',
 '6.34042',
 '6.3323584',
 '6.2594266',
 '6.4454327',
 '6.496004',
 '6.356628',
 '6.6280575',
 '6.4186583',
 '4.923395',
 '5.235688',
 '5.2628007',
 '5.2414894',
 '0.041052148',
 '0.05413327',
 '0.06695197',
 '0.058363825',
 '0.072986096',
 '0.08561023',
 '0.102280356',
 '0.12421692',
 '0.11714463',
 '0.12022918',
 '0.10492857',
 '0.085579515',
 '0.22021995',
 '0.21258359',
 '0.22380534',
 '0.21480602',
 '0.27815038',
 '0.17579731',
 '0.2927626',
 '0.4828663',
 '0.6113182',
 '0.5684056',
 '0.72891736',
 '0.76287675',
 '0.7358426',
 '0.64428496',
 '0.46363193',
 '0.48204285',
 '0.71268207',
 '0.6995089',
 '0.6558199',
 '0.6243505',
 '0.5296347',
 '0.56154835',
 '0.52895063',
 '0.47817305',
 '0.45701057',
 '0.55116254',
 '0.4648897',
 '0.43802312',
 '0.43778652',
 '0.42117858',
 '0.41569275',
 '0.44814283',
 '0.8568642',
 '0.92093813',
 '1.0760698',
 '1.0834786',
 '1.0893121',
 '1.1017437',
 '0.98766494',
 '0.94991744',
 '0.92799395',
 '0.97440386',
 '0.914801',
 '0.79760987',
 '0.8464459',
 '0.8689214',
 '0.92208517',
 '0.9866278',
 '0.9660866',
 '1.0303273',
 '0.9825774',
 '0.9605925',
 '0.97688556',
 '0.87261665',
 '0.78040165',
 '0.7446486',
 '0.6809788',
 '0.49424317',
 '0.56826746',
 '0.5654583',
 '5.655664',
 '5.289506',
 '5.940337',
 '5.79197',
 '6.0201273',
 '6.2288',
 '6.060323',
 '6.247229',
 '6.070692',
 '6.8724546',
 '7.329912',
 '7.1941266',
 '7.3877172',
 '8.484287',
 '8.943857',
 '9.67838',
 '9.811452',
 '9.648827',
 '9.482113',
 '9.864194',
 '9.164717',
 '9.022611',
 '8.794879',
 '9.780962',
 '9.706637',
 '8.874741',
 '8.944464',
 '9.8726845',
 '9.613563',
 '9.852858',
 '9.755176',
 '10.012469',
 '0.26864195',
 '0.42074326',
 '0.30909398',
 '0.35328513',
 '0.24726677',
 '0.43623376',
 '0.42770427',
 '0.4193339',
 '0.5481645',
 '0.5373517',
 '0.658744',
 '0.84223926',
 '1.7888441',
 '1.4490432',
 '1.5516219',
 '2.504276',
 '5.714567',
 '9.1219425',
 '15.7448435',
 '19.688433',
 '7.152148',
 '6.5643816',
 '5.7824883',
 '5.12352',
 '6.690514',
 '11.074167',
 '6.3193216',
 '7.28418',
 '7.664913',
 '6.325396',
 '2.2143776',
 '1.642643',
 '4.5233173',
 '1.2974504',
 '2.2582781',
 '3.856484',
 '3.8753188',
 '4.2961664',
 '4.4906898',
 '4.511603',
 '3.8331828',
 '3.9294703',
 '3.8674986',
 '3.9096968',
 '4.0004787',
 '3.9750183',
 '4.1571183',
 '4.382097',
 '4.451636',
 '4.674421',
 '4.7432637',
 '4.864015',
 '5.278511',
 '5.503338',
 '5.723982',
 '6.027829',
 '6.408216',
 '6.54638',
 '6.4950438',
 '6.614897',
 '6.440348',
 '6.3223624',
 '6.3813004',
 '6.32341',
 '6.396648',
 '6.51498',
 '6.6373863',
 '6.681476',
 '6.768622',
 '7.017083',
 '6.740573',
 '6.902878',
 '6.657135',
 '6.909023',
 '0.013673803',
 '0.032908835',
 '0.041893065',
 '0.026321769',
 '0.031573337',
 '0.03730976',
 '0.029855374',
 '0.042573165',
 '0,03507302',
 '0.058306683',
 '0.089572854',
 '0.06245207',
 '0.0895038',
 '0.10059324',
 '0.08947428',
 '0.09374776',
 '0.088586494',
 '0.09527532',
 '0.10954309',
 '0.061874352',
 '0.058640223',
 '0.044949133',
 '0.035060696',
 '0.08051388',
 '0.07901757',
 '0.12160134',
 '0,13154578',
 '0.2360082',
 '0.26492643',
 '0.26444587',
 '0.3945215',
 '0.37945464',
 '0.6034034',
 '0.43143836',
 '0.3115949',
 '0.46903446',
 '0.4500921',
 '0.50758815',
 '0.59021986',
 '0.5575416',
 '0.5284933',
 '0.509013',
 '0.5839936',
 '0.4323882',
 '0.49588075',
 '0.50725186',
 '0.55892307',
 '0.6886952',
 '0.8258431',
 '1.0618477',
 '0.89841384',
 '0.93455523',
 '0.83665067',
 '1.0261819',
 '1.2140063',
 '1.1976022',
 '1.2732416',
 '1.1010218',
 '0.53138864',
 '0.2962328',
 '0.18784678',
 '0.39744225',
 '0.6360484',
 '0.5249176',
 '0.6487387',
 '0.7638144',
 '0.99620444',
 '0.9960255',
 '0.9829984',
 '1.1556275',
 '1.0944129',
 '1.1017036',
 '1.0521537',
 '1.0397519',
 '1.0547066',
 '1.0867624',
 '1.1576643',
 '1.119883',
 '1.167924',
 '1.229445',
 '1.1909894',
 '1.1923398',
 '1.11146',
 '0.9720639',
 '0.922407',
 '0.94508845',
 '0.91897327',
 '0.88312054',
 '0,86872613',
 '0.9028329',
 '1.0613021',
 '0.9200045',
 '1.7582052',
 '2.0144029',
 '2.0394013',
 '1.9474617',
 '1.9993435',
 '2.113695',
 '2.3252912',
 '2.4561558',
 '2.2416515',
 '2.4413848',
 '2.392052',
 '2.4667575',
 '2.5454984',
 '2.335606',
 '2.557255',
 '2.6593328',
 '2.8089852',
 '2.8718717',
 '2.980885',
 '3.2859674',
 '3.4612136',
 '3.6627097',
 '3.6546595',
 '3.7521312',
 '3.750012',
 '3.6656525',
 '3.7933981',
 '3.7714992',
 '3.7798533',
 '4.0123534',
 '3.8789694',
 '3.5823743',
 '3.5731635',
 '3.5646577',
 '3.3138757',
 '3.3801806',
 '3.6711648',
 '3.8200974',
 '3.6261837',
 '3.4237704',
 '3.5436008',
 '3.607063',
 '3.4551',
 '3.4226372',
 '3.5721865',
 '3.692917',
 '3.7986495',
 '3.8303308',
 '4.0305786',
 '3.855236',
 '3.5916946',
 '3.2851217',
 '3.4999025',
 '4.046006',
 '4.1203923',
 '4.3992844',
 '4.337707',
 '4.634417',
 '4.361312',
 '4.54762',
 '4.5387554',
 '4.451076',
 '4.3788633',
 '4.410235',
 '4.326175',
 '4.044336',
 '3.969186',
 '3.6537664',
 '4.2175727',
 '4,4943867',
 '4.299799',
 '8.832011e-05',
 '0.00010720834',
 '6.9376845e-05',
 '8.593262e-05',
 '0.00046166775',
 '0.0013364782',
 '0.0018260301',
 '0.0019192299',
 '0.0025119476',
 '0.0031617072',
 '0.002826426',
 '0.0029325227',
 '0.0032594292',
 '0.0030869336',
 '0.009660993',
 '0.01098509',
 '0.009055714',
 '0.012170943',
 '0.013086264',
 '0.017505381',
 '0.016558615',
 '0.01991405',
 '0.022710022',
 '0.027936064',
 '0.028246393',
 '0.036576033',
 '0.03718469',
 '0.043220297',
 '0.045103792',
 '0.047072086',
 '0.053082146',
 '0.053399507',
 '0.057628326',
 '0.05856153',
 '0.06345299',
 '0.06789629',
 '0.076182574',
 '0.08310829',
 '0.08716196',
 '0.101224035',
 '0.10214635',
 '0.11628942',
 '0.1172928',
 '0.13436683',
 '0.17161825',
 '0.19262141',
 '0.1959334',
 '0,18749787',
 '0.18172158',
 '0.20031929',
 '0.17716438',
 '0.20021743',
 '0.22219701',
 '0.22150344',
 '0.22510841',
 '0.2312406',
 '0.25953275',
 '0.27934095',
 '0.2497916',
 '0.22716497',
 '0.23989041',
 '0.21874508',
 '0.086444',
 '0.07316447',
 '0.066110395',
 '0.07104394',
 '0.085854314',
 '0.09397665',
 '0.11094613',
 '0.10850647',
 '0.15578502',
 '0.19192174',
 '0.208783',
 '0.22284374',
 '0.30155143',
 '0.35929063',
 '0.40053102',
 '0,444208',
 '0.5318963',
 '0.59568447',
 '0.67567515',
 '0.6854013',
 '0.7169203',
 '0.71914864',
 '0.85441315',
 '0.7437685',
 '0.4043868',
 '0.4182036',
 '0.60095894',
 '0.62768173',
 '0.6970409',
 '0.8307709',
 '0.9797033',
 '1.0717827',
 '1.1321625',
 '1.1814514',
 '1.216502',
 '1.2907412',
 '1.4212921',
 '1.5127516',
 '1.6035019',
 '1.6566873',
 '1.6836365',
 '1.6943232',
 '1.6914326',
 '1.7206311',
 '1.789897',
 '1.847997',
 '1,9042583',
 '1.9558038',
 '1.9929872',
 '1.9994702',
 '2.0352902',
 '2,095545',
 '2.1839857',
 '2.2544608',
 '2.3049057',
 '2.3466268',
 '2.4179263',
 '2.4453003',
 '2.4472914',
 '2.4490037',
 '2.4165149',
 '2.487746',
 '2.422734',
 '2.4471617',
 '2.461691',
 '2.459555',
 '2.6211872',
 '2.4698963',
 '2.4531863',
 '2.770213',
 '2.5334718',
 '2.0420165',
 '1.6024374',
 '0.72690433',
 '0.7979213',
 '1.016661',
 '0.7625837',
 '1.0019927',
 '1.0656698',
 '0.9598779',
 '1.117025',
 '1.1453632',
 '1.0069239',
 '1.1370804',
 '1.2212219',
 '1.4719211',
 '1.7144572',
 '1.8833776',
 '1.4813462',
 '1.4509143',
 '1.6997676',
 '1.9668759',
 '1.893911',
 '1.917619',
 '1.8722998',
 '1.7825887',
 '1.9005892',
 '2.0008006',
 '2.1639683',
 '2.3506086',
 '2.5840561',
 '2.4869351',
 '2.5848775',
 '0.0',
 '9.577883',
 '14.721103',
 '8.278811',
 '9.329421',
 '18.375748',
 '14.804124',
 '18.650229',
 '12.416305',
 '10.607018',
 '13.320945',
 '11.259256',
 '11.610874',
 '12.58395',
 '11.909855',
 '10.177072',
 '9.435419',
 '11.563055',
 '10.738753',
 '14.057982',
 '15.750522',
 '13.304075',
 '14.623604',
 '13.103169',
 '9.382853',
 '19.890474',
 '10.348436',
 '8.784427',
 '9.188084',
 '9.434739',
 '8.95366',
 '9.947475',
 '5.0769243',
 '12.603837',
 '14.708233',
 '2.8211188',
 '9.678556',
 '10.227051',
 '7.5608516',
 '7.9814916',
 '7.8184905',
 '9.122505',
 '8.976114',
 '9.31321',
 '9.242035',
 '9.349359',
 '9.620471',
 '9.363043',
 '26.787004',
 '26.652435',
 '26.660248',
 '27.74074',
 '28.848864',
 '29.204588',
 '27.157389',
 '26.525524',
 ...]

In [97]:
emission_co2["unit_2"]=emission_co2["unit_2"].str.strip().str.replace(',','.')
emission_co2["unit_2"]=pd.to_numeric(emission_co2["unit_2"],errors='coerce')

In [98]:
emission_co2["Annual CO₂ emissions (per capita)"]=pd.to_numeric(emission_co2["Annual CO₂ emissions (per capita)"],errors='coerce')
emission_co2["Year"]=pd.to_numeric(emission_co2["Year"],errors='coerce')

In [99]:
emission_co2.rename(columns={"Annual CO₂ emissions (per capita)":'annual_emissions','Year':'year','Entity':'entity'},inplace=True)

**Manejo de fechas**

In [100]:
emission_co2["date"] = pd.to_datetime(emission_co2["date"], errors="coerce", utc=True)

In [101]:
emission_co2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26540 entries, 0 to 26539
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   entity            26540 non-null  object
 1   year              26490 non-null  float64
 2   annual_emissions  25206 non-null  float64
 3   date              26441 non-null  datetime64[ns, UTC]
 4   unit_2            25475 non-null  float64
dtypes: datetime64[ns, UTC](1), float64(3), object(1)
memory usage: 1.0+ MB

In [102]:
emission_co2.head()

        entity    year  annual_emissions                      date  unit_2
0  AFGHANISTAN  1949.0          0.001992 1949-01-01 00:00:00+00:00   0.002
1  AFGHANISTAN  1950.0          0.010837 1950-01-01 00:00:00+00:00   0.010
2  AFGHANISTAN  1951.0          0.011625 1951-01-01 00:00:00+00:00   0.012
3  AFGHANISTAN  1952.0          0.011468 1952-01-01 00:00:00+00:00   0.010
4  AFGHANISTAN  1953.0          0.013123 1953-01-01 00:00:00+00:00   0.013

#### **Manejo de valores nulos/faltantes**

In [103]:
# Ver nulos en el dataset
emission_co2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26540 entries, 0 to 26539
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   entity            26540 non-null  object
 1   year              26490 non-null  float64
 2   annual_emissions  25206 non-null  float64
 3   date              26441 non-null  datetime64[ns, UTC]
 4   unit_2            25475 non-null  float64
dtypes: datetime64[ns, UTC](1), float64(3), object(1)
memory usage: 1.0+ MB

*¿Qué hacer con lo datos nulos?*

In [104]:
# Eliminar filas con valores nulos
emission_co2.dropna(inplace=True)

In [105]:
# Reemplazar valores nulos 
emission_co2["year"].fillna(1950, inplace=True) # Recuerda inplace hace el cambio sin necesida de guardar explícitamente

C:\Users\roman\AppData\Local\Temp\ipykernel_21320\3384176658.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  emission_co2["year"].fillna(1950, inplace=True) # Recuerda inplace hace el cambio sin necesida de guardar explícitamente

> Podemos reemplazar los valores nulos por alguna estádisica de interés de los datos (mediana,percentil,media,etc)

In [106]:
avg_unit_2=emission_co2["unit_2"].mean()
emission_co2["unit_2"]=emission_co2["unit_2"].fillna(avg_unit_2) # Nota que aquí no se usa el inplace

In [107]:
emission_co2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 25113 entries, 0 to 26539
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   entity            25113 non-null  object
 1   year              25113 non-null  float64
 2   annual_emissions  25113 non-null  float64
 3   date              25113 non-null  datetime64[ns, UTC]
 4   unit_2            25113 non-null  float64
dtypes: datetime64[ns, UTC](1), float64(3), object(1)
memory usage: 1.1+ MB

#### **Manejo de duplicados**

In [108]:
# Detectar duplicados
emission_co2.duplicated().sum()

np.int64(140)

In [ ]:

# Eliminar duplicados
emission_co2.drop_duplicates(inplace=True) # Nota el uso de inplace

In [ ]:
emission_co2.info()

### 🔎 Filtrar, ordenar y resumir datos

In [69]:
emission_co2.head()

        entity  year  annual_emissions                      date  unit_2
0  AFGHANISTAN  1949          0.001992 1949-01-01 00:00:00+00:00   0.002
1  AFGHANISTAN  1950          0.010837 1950-01-01 00:00:00+00:00   0.010
2  AFGHANISTAN  1951          0.011625 1951-01-01 00:00:00+00:00   0.012
3  AFGHANISTAN  1952          0.011468 1952-01-01 00:00:00+00:00   0.010
4  AFGHANISTAN  1953          0.013123 1953-01-01 00:00:00+00:00   0.013

**Filtrar datos en pandas**

In [86]:
# Filtrar pacientes con mas de 40 años
emission_co2[emission_co2["year"] >1960 ]

            entity    year  annual_emissions                      date  unit_2
12     AFGHANISTAN  1961.0          0.053266 1961-01-01 00:00:00+00:00   0.053
13     AFGHANISTAN  1962.0          0.073220 1962-01-01 00:00:00+00:00   0.073
14     AFGHANISTAN  1963.0          0.073584 1963-01-01 00:00:00+00:00   0.074
15     AFGHANISTAN  1964.0          0.085442 1964-01-01 00:00:00+00:00   0.090
16     AFGHANISTAN  1965.0          0.100330 1965-01-01 00:00:00+00:00   0.100
...            ...     ...               ...                       ...     ...
26534       BHUTAN  2008.0          0.941708 2008-01-01 00:00:00+00:00   0.940
26535       POLAND  1992.0          9.533767 1992-01-01 00:00:00+00:00   9.530
26537     TANZANIA  1969.0          0.137663 1969-01-01 00:00:00+00:00   0.138
26538       GUYANA  1986.0          1.359503 1986-01-01 00:00:00+00:00   1.360
26539        HAITI  2000.0          0.196810 2000-01-01 00:00:00+00:00   0.197

[14183 rows x 5 columns]

In [109]:
#Operador AND & y operador OR |
emission_co2[(emission_co2["year"] >1960) &(emission_co2["entity"] =='AFGHANISTAN') ]

         entity    year  annual_emissions                      date  unit_2
12  AFGHANISTAN  1961.0          0.053266 1961-01-01 00:00:00+00:00   0.053
13  AFGHANISTAN  1962.0          0.073220 1962-01-01 00:00:00+00:00   0.073
14  AFGHANISTAN  1963.0          0.073584 1963-01-01 00:00:00+00:00   0.074
15  AFGHANISTAN  1964.0          0.085442 1964-01-01 00:00:00+00:00   0.090
16  AFGHANISTAN  1965.0          0.100330 1965-01-01 00:00:00+00:00   0.100
..          ...     ...               ...                       ...     ...
70  AFGHANISTAN  2019.0          0.285955 2019-01-01 00:00:00+00:00   0.286
71  AFGHANISTAN  2020.0          0.297063 2020-01-01 00:00:00+00:00   0.300
72  AFGHANISTAN  2021.0          0.256794 2021-01-01 00:00:00+00:00   0.257
73  AFGHANISTAN  2022.0          0.260180 2022-01-01 00:00:00+00:00   0.260
74  AFGHANISTAN  2023.0          0.265837 2023-01-01 00:00:00+00:00   0.270

[62 rows x 5 columns]

In [111]:
emission_co2[(emission_co2["year"] >1960) | (emission_co2["entity"] =='AFGHANISTAN') ]

            entity    year  annual_emissions                      date  unit_2
0      AFGHANISTAN  1949.0          0.001992 1949-01-01 00:00:00+00:00   0.002
1      AFGHANISTAN  1950.0          0.010837 1950-01-01 00:00:00+00:00   0.010
2      AFGHANISTAN  1951.0          0.011625 1951-01-01 00:00:00+00:00   0.012
3      AFGHANISTAN  1952.0          0.011468 1952-01-01 00:00:00+00:00   0.010
4      AFGHANISTAN  1953.0          0.013123 1953-01-01 00:00:00+00:00   0.013
...            ...     ...               ...                       ...     ...
26534       BHUTAN  2008.0          0.941708 2008-01-01 00:00:00+00:00   0.940
26535       POLAND  1992.0          9.533767 1992-01-01 00:00:00+00:00   9.530
26537     TANZANIA  1969.0          0.137663 1969-01-01 00:00:00+00:00   0.138
26538       GUYANA  1986.0          1.359503 1986-01-01 00:00:00+00:00   1.360
26539        HAITI  2000.0          0.196810 2000-01-01 00:00:00+00:00   0.197

[13471 rows x 5 columns]

**Ordenar datos**

In [110]:
# Ordenar de mayor a menor
emission_co2.sort_values(by="year", ascending=False)

,entity,year,annual_emissions,date,unit_2
74,AFGHANISTAN,2023.0,0.265837,2023-01-01 00:00:00+00:00,0.270
5137,COLOMBIA,2023.0,2.011398,2023-01-01 00:00:00+00:00,2.011
11531,ICELAND,2023.0,9.708070,2023-01-01 00:00:00+00:00,9.710
25459,VANUATU,2023.0,0.705832,2023-01-01 00:00:00+00:00,0.706
20267,SAINT VINCENT AND THE GRENADINES,2023.0,2.340626,2023-01-01 00:00:00+00:00,2.341
...,...,...,...,...,...
25780,WORLD,1750.0,0.012354,1750-01-01 00:00:00+00:00,0.012
17754,NORWAY,1750.0,0.000000,1750-01-01 00:00:00+00:00,0.000
10792,HIGH-INCOME COUNTRIES,1750.0,0.050397,1750-01-01 00:00:00+00:00,0.050
22797,TAIWAN,1750.0,0.000000,1750-01-01 00:00:00+00:00,0.000
1504,AUSTRALIA,1750.0,0.000000,1750-01-01 00:00:00+00:00,0.000

## 🚀 Para seguir aprendiendo :

---

- 📚 Vuelve a revisar este notebook y trata resolver por tu cuenta  nuevamente
- 💬 Recuerda que en Discord puedes dejar todos tus comentarios y dudas sobre el contenido del sprint en [`Discord`](https://discord.com/channels/1081207584104656986/1420849538196836472).
    - 📝 Si tienes preguntas sobre tu proyecto, usa el canal [`#project`](https://discord.com/channels/1081207584104656986/1420848813186351134) para recibir ayuda y compartir ideas.
    - 🤝 Aprovecha el espacio de `CoLearning` para aclarar tus dudas junto con otros estudiantes e instructores: [Co-Learning](https://discord.com/channels/1081207584104656986/1197953851391746119).
    - En tus preguntas recuerda etiquetar a `@Dataconsulta` y ubica tu pregunta de acuerdo a `Sprint/Capitulo/Seccion`
- 📅 ¿Necesitas ayuda personalizada? Puedes agendar una sesión `1:1` conmigo aquí: [1:1 Roman Castillo](https://scheduler.zoom.us/roman-castillo/1-1-roman-castillo).

- Por último hazme paro y responde la encuesta al final de la sesión, me sirve para poder ayudarte mejor 

¡Sigue practicando y no dudes en pedir apoyo cuando lo necesites! 💪✨