In [1]:
import glob, os
import pandas as pd

In [2]:
PATH ='./data'

## Academy

In [5]:
patron=os.path.join(PATH,'academy*')
archivos = glob.glob(patron)

In [8]:
archivos

['./data\\academy_course_catalog.csv',
 './data\\academy_instructors.csv',
 './data\\academy_sessions_jan_jun_2024.csv']

In [19]:
pd.read_csv(archivos[1])

  Instructor    Seniority  Certifications   Hire_Date
0     Marcos       Senior               3  2019-03-01
1      Lucía       Senior               2  2020-01-15
2      Carla  Semi-Senior               2  2021-06-01
3      Diego       Senior               4  2018-09-10
4    Valeria  Semi-Senior               3  2022-02-20

In [ ]:
pd.read_csv(archivos[2])[['Session_ID', 'Date', 'Course', 'Instructor', 'Modality', 'Day',
       'Start_Time', 'End_Time', 'Branch', 'Capacity', 'Students_Enrolled',
       'Attendance_Rate', 'Cancelations', 'Price_USD', 'Revenue_USD']]

Index(['Session_ID', 'Date', 'Course', 'Instructor', 'Modality', 'Day',
       'Start_Time', 'End_Time', 'Branch', 'Capacity', 'Students_Enrolled',
       'Attendance_Rate', 'Cancelations', 'Price_USD', 'Revenue_USD'],
      dtype='object')

In [ ]:
pd.read_csv(archivos[2]).groupby(['Date','Instructor'],as_index=False).agg(cc=('Course','count')).sort_values(by='cc',ascending=False)

           Date Instructor  cc
0    2024-01-01     Marcos   1
1    2024-01-01    Valeria   1
2    2024-01-02      Carla   1
3    2024-01-02      Lucía   1
4    2024-01-02    Valeria   1
..          ...        ...  ..
310  2024-06-27    Valeria   1
311  2024-06-28      Lucía   1
312  2024-06-28     Marcos   1
313  2024-06-29      Carla   1
314  2024-06-29      Lucía   1

[315 rows x 3 columns]