In [16]:
import pandas as pd
import numpy as np
import uuid
import random
import os
from datetime import datetime, timedelta

In [9]:
def generar_costos_campañas(
    k=10,
    mu_base=1000, sigma_base=200,
    scale_dia=50,
    shape_interaccion=2.0, scale_interaccion=30.0,
    random_state=None
):
    """
    Genera un DataFrame con costos simulados para campañas.

    Parámetros:
    - k: número de campañas
    - mu_base, sigma_base: media y desviación estándar del costo base (Normal)
    - scale_dia: parámetro de escala para el costo por día activo (Exponencial)
    - shape_interaccion, scale_interaccion: parámetros de la distribución Gamma para el costo por interacción
    - random_state: semilla opcional para reproducibilidad

    Retorna:
    - DataFrame con columnas: id_campaña, costo_base_campaña, costo_por_dia_activo_campaña, costo_por_interaccion_campaña
    """
    rng = np.random.default_rng(random_state)

    data = {
        'id_campaña': np.arange(1, k + 1),
        'costo_base_campaña': np.abs(rng.normal(mu_base, sigma_base, size=k)),
        'costo_por_dia_activo_campaña': rng.exponential(scale=scale_dia, size=k),
        'costo_por_interaccion_campaña': rng.gamma(shape=shape_interaccion, scale=scale_interaccion, size=k),
    }

    return pd.DataFrame(data)

In [227]:
random.random()

0.5703547001377148

In [228]:
def generar_fechas_aleatorias(start_date, end_date, n_dates=1):
    if isinstance(start_date, str):
        start_date = datetime.fromisoformat(start_date).replace(hour=0, minute=0, second=0, microsecond=0)
    if isinstance(end_date, str):
        end_date = datetime.fromisoformat(end_date).replace(hour=0, minute=0, second=0, microsecond=0)

    delta_seconds = int((end_date - start_date).total_seconds())
    

    segundos_aleatorios = np.random.choice(range(delta_seconds), n_dates)
    fechas = [start_date + timedelta(seconds=int(s)) for s in sorted(segundos_aleatorios)]
    
    return fechas

def generar_fecha_entre(start_date, end_date):
    if isinstance(start_date, str):
        start_date = datetime.fromisoformat(start_date).replace(hour=0, minute=0, second=0, microsecond=0)
    if isinstance(end_date, str):
        end_date = datetime.fromisoformat(end_date).replace(hour=0, minute=0, second=0, microsecond=0)
    delta_seconds = int((end_date - start_date).total_seconds())*random.random()
    return start_date + timedelta(seconds=int(delta_seconds))

def generate_purchase():
    product_prices =[20,49,99,299,499]
    n_products = random.randint(1,len(product_prices))
    items =0
    purchase =0
    for _ in range(n_products):
        idx = random.randint(1,len(product_prices))-1
        current_item= product_prices[idx]
        current_items_amount =random.randint(1,5)
        current_purchase = current_items_amount*current_item
        items += current_items_amount
        purchase += current_purchase
    return [items,purchase]

## Params

In [ ]:
# params

n_users=50000
n_visits_mean= 7
n_campaigns = 6
rate_convertions = 0.23
days_of_data=90
p_campaigns = np.random.choice([2,3,5,7,11,13],n_campaigns)
p_campaigns=p_campaigns/p_campaigns.sum()
p_campaigns_convertion = np.random.choice([3,5,7],n_campaigns)
p_campaigns_convertion=p_campaigns/p_campaigns.sum()
end_date= datetime.now().strftime("%Y-%m-%d")
start_date = (datetime.now() - timedelta(days=days_of_data)).strftime("%Y-%m-%d")

In [231]:
n_campaigns =5
seed=42
days_of_data=120
lambda_orders =1.6
p_paid = 0.45

# Dates
end_date= datetime.now().strftime("%Y-%m-%d")
start_date = (datetime.now() - timedelta(days=days_of_data)).strftime("%Y-%m-%d")

# params
rng = np.random.default_rng(seed)
visits_per_campaign = rng.gamma(shape=334, scale=289, size=n_campaigns).astype(int).tolist()
visits_convertion_prob = rng.beta(a=7,b=15,size=n_campaigns)
convertion_order_prob = rng.beta(a=7,b=28,size=n_campaigns)

## Interactions df

In [234]:
interactions_report=os.path.join('..','datasets','interactions.csv')

interactions=(pd.DataFrame({
    'campaign_id':[str(i+1) for i in range(n_campaigns)],
    'visits' : visits_per_campaign,
    'p_convertion': visits_convertion_prob
              })
       .assign(
        visit_ts = lambda df: df.visits.apply(lambda x :generar_fechas_aleatorias(start_date=start_date,end_date=end_date,n_dates=x))
    )
    .explode('visit_ts')
    .reset_index(drop=True)
    .reset_index()
    .assign(
        is_convertion = lambda df: df.p_convertion.apply(lambda x: rng.binomial(n=1,p=x)),
        uuid_user = lambda df: df.apply( lambda x:  str(uuid.uuid5(uuid.NAMESPACE_DNS,str(f"user-{x['index']}"))) if x['is_convertion'] else None , axis=1 )
    )
    .drop(columns=['visits','p_convertion','index'])
    .sort_values(by='visit_ts')
    
     )

interactions.to_csv(interactions_report,index=False)

interactions.head()

,campaign_id,visit_ts,is_convertion,uuid_user
382090,5,2025-02-16 00:00:03,0,None
284984,4,2025-02-16 00:00:13,0,None
284985,4,2025-02-16 00:00:24,1,dfc54fb8-45cc-5fd5-99ac-f1f4d49d76ab
198492,3,2025-02-16 00:01:01,1,1cb88369-8c8a-54c4-8edb-626a5c344df2
382091,5,2025-02-16 00:01:18,0,None

## Orders csv

In [235]:
orders_df_2=os.path.join('..','datasets','orders_v2.csv')
(
    interactions
        .query("uuid_user.notnull()")
        .assign(
            n_orders = lambda df: df.uuid_user.apply(lambda x: np.random.poisson(lam=lambda_orders))
        )
        .query("n_orders >0")
        .assign(
        uuid_order = lambda df: df.apply(lambda row: [ str(uuid.uuid5(uuid.NAMESPACE_DNS,str(f"user-{row['uuid_user']}-{i}"))) for i in range(row['n_orders'])],axis=1)
        )
        .explode('uuid_order')
        .assign(
            paid = lambda df: df.uuid_order.apply(lambda x: rng.binomial(n=1,p=p_paid))
        )
    .assign(
        transaction = lambda df: df.apply(lambda x: generate_purchase(),axis=1),
        items = lambda df: df.transaction.apply(lambda x: x[0]),
        amount = lambda df: df.transaction.apply(lambda x: x[1]),
        ts_order= lambda df: df.apply(lambda x: generar_fecha_entre(x['visit_ts'],end_date=end_date),axis=1)
    )
    .drop(columns=['transaction','n_orders','is_convertion','campaign_id','visit_ts'])
    .to_csv(orders_df_2,index=False)
)

In [15]:
visits_df=os.path.join('..','datasets','visits.csv')
(
    pd.DataFrame( [i for i in range(n_users)] , columns=['user_id'])
    .assign(
        n_visits = lambda df: df.user_id.apply(lambda x: (np.random.poisson(lam=n_visits_mean,size=1)+1)[0]),
        uuid_user = lambda df: df.user_id.apply(lambda x: str(uuid.uuid5(uuid.NAMESPACE_DNS,str(f"user-{x}")))),
        ts_visits = lambda df: df.n_visits.apply(lambda x: generar_fechas_aleatorias(start_date=start_date,end_date=end_date,n_dates=x))
    )
    .drop(
        columns=['user_id','n_visits']
    )
    .explode('ts_visits')
        .assign(
        campaign = lambda df: df.uuid_user.apply(lambda x: np.random.multinomial(1,p_campaigns).argmax()+1),
        uuid_interaction = lambda df: df.apply(lambda row: str(uuid.uuid5(uuid.NAMESPACE_DNS,str(f"user-{row['uuid_user']}-{row['campaign']}-{row['ts_visits']}"))),axis=1),
        convertion = lambda df: df.campaign.apply(lambda x: np.random.binomial(1,p_campaigns_convertion[x-1]))
    )
    .sort_values('convertion')
    #.to_csv(visits_df,index=False)
    
)

,uuid_user,ts_visits,campaign,uuid_interaction,convertion
3,8e366a8d-6e18-50fd-98d9-2efd6d246b24,2025-05-13 05:13:57,1,83969fc8-853e-5a56-ada1-f8bca08f93df,0
3,8e366a8d-6e18-50fd-98d9-2efd6d246b24,2025-05-16 00:47:05,6,e0694fb2-b6fb-5475-bfec-d5cb09cf5b8b,0
3,8e366a8d-6e18-50fd-98d9-2efd6d246b24,2025-05-17 00:41:37,2,a8be1aa2-f00c-5096-8691-c2366f4a771d,0
3,8e366a8d-6e18-50fd-98d9-2efd6d246b24,2025-05-18 02:17:16,4,dae02a0d-6a69-5a90-b242-3a55e7fa50d9,0
3,8e366a8d-6e18-50fd-98d9-2efd6d246b24,2025-05-23 17:51:25,1,59833fe3-65dd-55c0-aece-fba1e736b607,0
...,...,...,...,...,...
49994,1e01fb6e-e3ad-57c1-9134-2267ff4227d3,2025-06-09 12:50:12,1,aba17f16-4e49-57d2-aadd-d8e404840f0b,1
6,5d7e3982-b4cf-5ca6-9734-744833b910a3,2025-05-14 20:55:26,1,3ab504c9-2cdd-5081-954c-32d974e032a6,1
0,ffbe64a4-dbba-58b8-a95c-1dddc95c971b,2025-06-13 14:51:30,4,4bb3de90-477a-5f7b-8a53-27066e261053,1
1,d35a2a2a-d1d1-55ed-90a7-348c3da59deb,2025-05-17 08:06:14,1,3ad29223-cd04-5280-963a-c1b31c2bbd40,1
49998,3db93bed-0d8c-5659-adec-5342a723b967,2025-05-23 10:05:08,2,b8ba5961-9a6f-525a-8cc8-185fc1c39dc0,1

In [66]:
orders_df=os.path.join('..','datasets','orders.csv')


(pd.read_csv(visits_df)
    .query("convertion == 1")
    .assign(
        end_date = lambda df: pd.to_datetime(df.ts_visits, errors='coerce') + timedelta(days=10),
        transaction_ts = lambda df: df.apply(lambda row: generar_fechas_aleatorias(row['ts_visits'],row['end_date'],1),axis=1)
    )
    .explode("transaction_ts")[['uuid_interaction','transaction_ts']]
    .assign(
        transaction = lambda df: df.apply(lambda x: generate_purchase(),axis=1),
        items = lambda df: df.transaction.apply(lambda x: x[0]),
        amount = lambda df: df.transaction.apply(lambda x: x[1]),
    )
    .drop(columns=['transaction'])
    .to_csv(orders_df,index=False)
    
)

In [5]:
campaigns_df=os.path.join('..','datasets','campaigns_details.csv')
generar_costos_campañas(k=n_campaigns,mu_base=90000,sigma_base=100,scale_dia=500,shape_interaccion=11,scale_interaccion=8).to_csv(campaigns_df,index=False)